# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-alpine

# Set working directory
WORKDIR /app

# Install build dependencies and curl
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev curl

# Upgrade pip
RUN pip install --upgrade pip

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install  --no-cache -r requirements.lock


# Default command
CMD ["python", "main.py"]
